language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
cache:
  cargo: true
  timeout: 900
  directories:
    - $HOME/libsodium
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
matrix:
  allow_failures:
    - nightly

install:
  - sh ./.travis-install.sh

script:
- cargo test --all-features
